const isElectron = window.api !== undefined;

const getAppHeight = () => {
  if (typeof window !== 'undefined' && /Mobi|Android/i.test(navigator.userAgent)) {
    return `${window.innerHeight}px`;
  }
  return isElectron ? 'calc(100vh - 30px)' : '100vh';
};

export const layoutStyles = {
  appContainer: {
    width: '100vw',
    height: getAppHeight(),
    bg: 'white',
    color: 'gray.800',
    overflow: 'hidden',
    position: 'relative',
    display: 'flex',
    flexDirection: { base: 'column', md: 'row' },
  },
  mobileLayout: {
    live2d: {
      flex: 'none',
      minHeight: '35vh',
      maxHeight: '45vh',
      position: 'relative' as const,
      overflow: 'hidden',
      width: '100%',
    },
    headerButtons: {
      width: '100%',
      p: '3',
      bg: 'white',
      borderBottom: '1px solid',
      borderColor: 'gray.200',
      display: 'flex',
      justifyContent: 'flex-start',
      gap: '2',
      boxShadow: 'sm',
    },
    chatPanel: {
      flex: '1',
      overflow: 'auto',
      bg: 'gray.900',
      display: 'flex',
      flexDirection: 'column' as const,
    },
    footer: {
      width: '100%',
      minHeight: '80px',
      maxHeight: '35vh',
      bg: 'white',
      borderTop: '1px solid',
      borderColor: 'gray.200',
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      p: '3',
      '& textarea': {
        flex: '1',
        minHeight: '50px',
        maxHeight: 'calc(35vh - 24px)',
        resize: 'vertical',
      },
      '& .input-container': {
        display: 'flex',
        flexDirection: 'column',
        flex: '1',
        minHeight: '0',
      }
    },
  },
  sidebar: {
    position: 'relative' as const,
    width: { base: '100%', md: '440px' },
    height: { base: 'auto', md: '100%' },
    bg: 'gray.50',
    borderRight: '1px solid',
    borderColor: 'gray.200',
    overflow: 'auto',
    flexShrink: 0,
    transition: 'all 0.3s ease-in-out',
    display: { base: 'none', md: 'block' },
  },
  mainContent: {
    flex: 1,
    height: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    overflow: 'hidden',
  },
  canvas: {
    position: 'relative',
    width: '100%',
    flex: 1,
    height: 'calc(100% - 120px)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    willChange: 'transform',
  },
  footer: {
    width: '100%',
    height: '120px',
    minHeight: '120px',
    maxHeight: '120px',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform',
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  toggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: 'whiteAlpha.100',
    _hover: { bg: 'whiteAlpha.200' },
    borderLeftRadius: 0,
    borderRightRadius: 'md',
    zIndex: 10,
  },
  canvasHeight: (isFooterCollapsed: boolean) => ({
    height: isFooterCollapsed ? 'calc(100% - 24px)' : 'calc(100% - 120px)',
  }),
  sidebarToggleButton: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: '60px',
    bg: 'gray.800',
    borderLeftRadius: 0,
    borderRightRadius: 'md',
    zIndex: 10,
  },
  collapsedFooter: {
    height: { base: '20px', md: '24px' },
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  windowsTitleBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '30px',
    backgroundColor: 'gray.800',
    paddingX: '10px',
    css: { '-webkit-app-region': 'drag' },
  },
  macTitleBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '30px',
    backgroundColor: 'gray.800',
    css: {
      '-webkit-app-region': 'drag',
      '-webkit-user-select': 'none',
    },
  },
  titleBarTitle: {
    fontSize: 'sm',
    color: 'whiteAlpha.800',
    textAlign: 'center',
  },
  titleBarButtons: {
    display: 'flex',
    gap: '1',
  },
  titleBarButton: {
    size: 'sm',
    variant: 'ghost',
    color: 'whiteAlpha.800',
    css: { '-webkit-app-region': 'no-drag' },
    _hover: { backgroundColor: 'whiteAlpha.200' },
  },
  closeButton: {
    size: 'sm',
    variant: 'ghost',
    color: 'whiteAlpha.800',
    css: { '-webkit-app-region': 'no-drag' },
    _hover: { backgroundColor: 'red.500' },
  },
} as const;
