export const canvasStyles = {
  background: {
    container: {
      position: 'relative' as const,
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      pointerEvents: 'auto',
      borderRadius: 'xl',
      bg: 'transparent',
    },
    image: {
      position: 'absolute',
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover',
      zIndex: 1,
    },
    video: {
      position: 'absolute' as const,
      top: '0',
      left: '0',
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      zIndex: 1,
      transform: 'scaleX(-1)' as const,
    },
  },
  canvas: {
    container: {
      position: 'relative',
      width: '100%',
      height: '100%',
      zIndex: '1',
      pointerEvents: 'auto',
    },
  },
  subtitle: {
    container: {
      position: 'absolute',
      bottom: '30px',
      left: '50%',
      transform: 'translateX(-50%)',
      backgroundColor: 'rgba(255, 255, 255, 0.65)',
      padding: '15px 30px',
      borderRadius: '12px',
      minWidth: '60%',
      maxWidth: '95%',
      zIndex: 2,
      backdropFilter: 'blur(12px)',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.03), 0 1px 3px rgba(0, 0, 0, 0.05)',
      border: '1px solid',
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    text: {
      color: 'gray.800',
      fontSize: '1.5rem',
      textAlign: 'center',
      lineHeight: '1.4',
      whiteSpace: 'pre-wrap',
      fontWeight: 'medium',
      textShadow: '0 1px 2px rgba(0, 0, 0, 0.03)',
    },
  },
  wsStatus: {
    container: {
      position: 'absolute',
      top: '20px',
      left: '20px',
      zIndex: 2,
      padding: '8px 16px',
      borderRadius: '20px',
      fontSize: '14px',
      fontWeight: 'medium',
      color: 'white',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        opacity: 0.8,
      },
    },
  },
  modelSelector: {
    container: {
      position: 'absolute',
      top: '20px',
      right: '20px',
      zIndex: 2,
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    button: {
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '20px',
      fontSize: '14px',
      fontWeight: 'medium',
      transition: 'all 0.2s',
      cursor: 'pointer',
      userSelect: 'none',
      _hover: {
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
      },
    },
    menu: {
      container: {
        backgroundColor: 'white',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        padding: '4px 0',
      },
      item: {
        padding: '8px 16px',
        cursor: 'pointer',
        _hover: {
          backgroundColor: 'gray.100',
        },
      },
    },
  },
};
